language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - "nothing to install"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
 - docker build -t bezag/udagram-users .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push bezag/udagram-users
